version: '3.8'

services:
  social-media:
    build: .
    ports:
      - "8085:8082"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATA_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - socials-network

  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SOCIALS_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sm-data:/var/lib/mysql
    networks:
      - socials-network
      
volumes:
  sm-data:

networks:
  socials-network:
    name: social-media-network
